### ISSUE TITLE
Have a `fix` option

### ISSUE THREAD

**Issue by Noviny** [atlassian/stricter#107]
I was looking at porting some rules over from [manypkg](https://github.com/thinkmill/manypkg) for use in a project using stricter, and was immediately caught out by not having a `fix` command for rules I know I could fix.

Is there a chance we get support for having rules that can be auto-fixed instead of relying on users to resolve errors?

🙏 if it's there and I missed it.

**Comment by Li0liQ** [comment]
Absolutely. The fix possibility is planned to be added in the next release (by the end of March).
It's not there yet, sorry.

**Comment by Noviny** [comment]
All good. Super glad to hear this is coming.

**Comment by Li0liQ** [comment]
Fixed in [0.4.2](https://github.com/atlassian/stricter/releases/tag/0.4.2).
