### ISSUE TITLE
Add example for `tangerine/project-structure` rule

### ISSUE THREAD

**Issue by tobiastimm** [atlassian/stricter#213]
Unfortunately, every link within the README on npm is linking to an URL not available for the public.
Would be cool, if you could add a full example or a template on how to use that plugin.

https://www.npmjs.com/package/stricter-plugin-tangerine?activeTab=readme

**Comment by Li0liQ** [comment]
The readme for `tangerine/project-structure` rule is distributed as a part of `stricter-plugin-tangerine` package.
You can read find it at `node_modules/stricter-plugin-tangerine/src/rules/project-structure/README.md` or online at [unpkg.com](https://unpkg.com/browse/stricter-plugin-tangerine@0.2.0/src/rules/project-structure/README.md).
